import { expect, test } from '@playwright/test';

const ROUTE = '/work/projects/collaborative-whiteboard';

test('local canvas, document lifecycle and readable article', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(ROUTE);
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Editable Whiteboard and Operation Log');
  await expect(page.getByTestId('object-count')).toHaveText('10 objects');
  await expect(page.getByRole('status')).toHaveText('Saved on this device');
  const canvas = page.getByLabel('Editable whiteboard');
  await expect(canvas).toBeVisible();
  expect(await canvas.evaluate((element) => {
    const surface = element as HTMLCanvasElement;
    const pixels = surface.getContext('2d')!.getImageData(0, 0, surface.width, surface.height).data;
    const colors = new Set<string>();
    for (let i = 0; i < pixels.length; i += 64) colors.add(`${pixels[i]},${pixels[i + 1]},${pixels[i + 2]},${pixels[i + 3]}`);
    return colors.size;
  })).toBeGreaterThan(5);
  await page.getByRole('button', { name: 'Select rectangle draft', exact: true }).click();
  await page.getByLabel('X position', { exact: true }).fill('120');
  await page.getByRole('button', { name: 'Apply properties' }).click();
  await expect(page.getByLabel('X position', { exact: true })).toHaveValue('120');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByLabel('X position', { exact: true })).toHaveValue('90');
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(page.getByLabel('X position', { exact: true })).toHaveValue('120');
  await page.getByRole('button', { name: 'Ellipse tool' }).click();
  await page.getByRole('button', { name: 'Add object' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('11 objects');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export JSON' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('collaborative-whiteboard.trace.v1.json');
  const stream = await download.createReadStream();
  expect(stream).not.toBeNull();
  const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  const exported = Buffer.concat(chunks);
  expect(JSON.parse(exported.toString()).mode).toBe('local-single-tab');
  await page.getByRole('button', { name: 'Clear board' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('0 objects');
  await page.getByLabel('Import trace file').setInputFiles({ name: 'trace.json', mimeType: 'application/json', buffer: exported });
  await expect(page.getByTestId('object-count')).toHaveText('11 objects');
  await page.reload();
  await expect(page.getByTestId('object-count')).toHaveText('11 objects');
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: 'Reset board' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('10 objects');
  await expect(page.getByTestId('log-count')).toHaveText('0 commands');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.locator('#method').scrollIntoViewIfNeeded();
  await expect(page.getByRole('heading', { name: 'A scene graph, not a history of pixels' })).toBeVisible();
  expect(errors).toEqual([]);
  await page.locator('#demo').scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('output', 'playwright', `collaborative-whiteboard-${testInfo.project.name}.png`), fullPage: true });
});
