import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';
import { collectErrors } from './consoleErrors';

test('mission approval, fault response, content hashing and replay execute in browser', async ({ page }) => {
  const errors = collectErrors(page);
  await page.goto('/work/projects/mission-governance');
  await expect(page.getByRole('button', { name: 'Start simulation', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Validate mission', exact: true }).click();
  await expect(page.getByTestId('mission-state')).toHaveText('awaiting_approval');
  await page.getByRole('button', { name: 'Approve simulation', exact: true }).click();
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click();
  await page.getByRole('button', { name: 'Step mission', exact: true }).click();
  await expect(page.getByTestId('mission-progress')).toHaveText('1 / 4');
  await page.getByRole('button', { name: 'Pause mission', exact: true }).click();
  await expect(page.getByTestId('mission-state')).toHaveText('paused');
  await page.getByRole('button', { name: 'Resume mission', exact: true }).click();
  await page.getByRole('button', { name: 'Inject fault', exact: true }).click();
  await page.getByRole('button', { name: 'Step mission', exact: true }).click();
  await expect(page.getByTestId('mission-state')).toHaveText('rtl');
  await page.getByRole('button', { name: 'Verify replay', exact: true }).click();
  await expect(page.getByText('All four content hashes and deterministic replay match.', { exact: true })).toBeVisible();
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export replay', exact: true }).click();
  const file = await (await pending).path();
  expect(file).toBeTruthy();
  const bundle = JSON.parse(await readFile(file!, 'utf8'));
  expect(bundle.version).toBe('mission-governance.bundle.v1');
  expect(JSON.parse(bundle.files['final-state.json']).state).toBe('rtl');
  await page.getByText('Verify an exported bundle', { exact: true }).click();
  bundle.files['events.json'] += ' ';
  await page.getByRole('textbox', { name: 'Replay bundle JSON', exact: true }).fill(JSON.stringify(bundle));
  await page.getByRole('button', { name: 'Verify imported bundle', exact: true }).click();
  await expect(page.getByText('Content hash mismatch: events.json.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Reset mission', exact: true }).click();
  await expect(page.getByTestId('mission-state')).toHaveText('draft');
  await expect(page.getByRole('button', { name: 'Start simulation', exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});
