import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import Inspector from '@/components/projects/spreadsheet-reasoning/Inspector';
import styles from '@/components/projects/spreadsheet-reasoning/inspector.module.css';
import { analyze, compareGold, freshSession } from '@/lib/projects/spreadsheet-reasoning/engine';
import project from './project.json';

export const metadata: Metadata = {
  title: project.title,
  description: project.summary,
  alternates: { canonical: `/work/projects/${project.slug}` },
};

const sourceRoot = 'https://github.com/Sahil170595/Banterblogs/blob/codex/demo-spreadsheet-reasoning/banterblogs-nextjs/src/lib/projects/spreadsheet-reasoning';

export default function SpreadsheetReasoningPage() {
  const session = freshSession(), result = analyze(session), score = compareGold(session, result)!;
  return <main className={styles.page}>
    <nav className={styles.nav} aria-label="Project navigation">
      <Link href="/work" className={styles.back}><ArrowLeft size={16} aria-hidden="true" />Work</Link>
      <a href="#demo">Inspector</a><a href="#underlying">Underlying system</a><a href="#findings">Findings</a><a href="#method">Method</a><a href="#reproduce">Reproduce</a>
    </nav>
    <h1>{project.title}</h1>
    <p className={styles.intro}>Final in scope is not always final in a dependency graph. A deterministic browser adaptation with freshly authored sheets, explicit rule votes, and prune-only adjudication. No live model inference.</p>
    <Inspector />
    <article className={styles.article} aria-label="Technical write-up">
      <section id="underlying">
        <h2>Underlying system</h2>
        <p>The underlying work was a typed Python workbook-classification and evaluation system, not an eleven-cell arithmetic exercise. It ingested paired spreadsheet snapshots, a changed-cell candidate set, and task-specific labeling context. Workbook extraction read formula expressions and cached values separately; it did not claim to recalculate Excel. The output was a validated partition of candidate cells into final and intermediate values, with per-sheet failure and usage records. The browser edition below isolates inspectable mechanics from that larger model-assisted pipeline.</p>
        <h3>The implemented pipeline</h3>
        <ol>
          <li><strong>Ingest and establish the universe.</strong> Load workbook structure, cached values, formulas, formatting, and changed-cell candidates. Content-hash extraction caches avoid repeatedly parsing unchanged files. Candidate membership is established before classification rather than letting a model invent arbitrary cell addresses.</li>
          <li><strong>Resolve evidence globally.</strong> Tokenize formulas, build precedents and dependents across sheets, and derive fan-in/out, aggregation, formatting, and label features. Normalize formulas into relative patterns so a repeated row of periods can be represented once. Parsing warnings and fallback sketches remain observable rather than being mistaken for exact normalization.</li>
          <li><strong>Encode and classify.</strong> Select row or cell grouping from structural signals, preserve labels and section context during compression, and split large context by section. Async model calls share a concurrency limit, retry and schema-correction machinery, and atomic response caches. Repeated votes have separate cache identities so a cached response cannot masquerade as multiple independent samples.</li>
          <li><strong>Compose, route, and constrain.</strong> The implementation includes consensus intersection, a weak-supervision label model, and a sheet-structural router over precision- and recall-oriented model-assisted variants. The router uses density, cross-sheet references, input formatting, and sheet shape rather than private task identities. Deterministic support/reference guards and selectively applied prune-only adjudication constrain proposed finals.</li>
          <li><strong>Score and diagnose.</strong> The harness emits final-label confusion counts, pooled and task-macro metrics, alternative scoring coverage, row-grouped errors, and sheet-clustered bootstrap intervals. Gold is excluded from prediction-time file access. Predictions can be re-scored offline without replaying provider calls.</li>
        </ol>
        <h3>Recorded original result, with its limits</h3>
        <p>A preserved development evaluation dated <strong>7 July 2026</strong> records the structural-router variant over <strong>five task bundles and 24 sheets</strong>. Under labeled-candidate scoring it reports <strong>precision 0.970, recall 0.920, and micro F1 0.945</strong>, with 1,543 true positives, 47 false positives, and 134 false negatives. The same manifest reports <strong>task-macro F1 0.885</strong>, so the stronger pooled number must not hide variation across tasks. A stricter candidate-coverage score gives micro F1 0.941.</p>
        <p>The saved sheet-cluster bootstrap uses 1,000 resamples and reports an F1 interval of <strong>[0.876, 0.982]</strong>. This is uncertainty within that recorded development corpus, not uncertainty over all future spreadsheet domains. I verified these values from the preserved evaluation artifact for this write-up; they are not a new provider run, not scores from the browser fixture, and not a pristine held-out estimate. Routing thresholds and other operating choices were developed against the same small corpus. Sanitized full source is a separate publication step; no original workbook or model response is shipped here.</p>
        <h3>What the experiments taught me</h3>
        <p>The useful distinction was between sampling instability and convention error. Repeated votes helped suppress unstable whole-sheet decisions, but consensus could still reinforce the wrong interpretation of final in scope. Development ablations also found that global prune-only review could remove legitimate outputs; applying the same machinery only to structurally appropriate sheets was a more defensible design. Task-profile suggestions could inflate output proposals, making context isolation a precision concern rather than just a token-saving optimization.</p>
        <p>The weak-supervision implementation learned labeling-function reliability without consuming gold in its EM updates, but its class-prior operating point was chosen with development labels. That makes it a tuned component, not a leak-free end-to-end discovery of class balance. Its intended value was ranking ambiguous rows for escalation, not treating a fixed probability cutoff or self-reported model confidence as universally calibrated. The broader lesson was to expose candidate coverage, routing choices, and failure modes alongside the headline score.</p>
        <h3>What this edition exposes and omits</h3>
        <p>This edition exposes dependency topology, a checkpoint that remains meaningful despite consumers, an irrelevant sink, abstaining rule evidence, competing decision gates, and prune-only membership. It adds real bounded arithmetic recomputation so input edits visibly propagate. It omits original workbook ingestion, row compression, model inference, trained weak-label reliability, conformal calibration, and the full structural router. Its ballots are newly authored illustrations, not sanitized original model votes. The two result sets below are deliberately separate: a dated system-development record above and a transparent synthetic correctness fixture below.</p>
      </section>
      <section id="findings">
        <h2>When is a spreadsheet value final?</h2>
        <p>A cell can be numerically correct and still be the wrong thing to highlight. A margin subtotal may be a meaningful output for one section while also feeding a later calculation. Conversely, a scratch calculation can have no consumers at all without being an important result. The engineering problem is therefore not just formula evaluation: it is recovering the scope in which a value is an output.</p>
        <p>In the larger classification pipeline I implemented, changed cells defined the candidate universe. Workbook-wide dependencies supplied structural evidence, row patterns compressed repeated formulas, and sheet-level classification supplied the semantic judgment that the graph alone could not establish. I compared rules, repeated model votes, weak supervision, consensus, and structural routing rather than treating one prompt as a complete system. This public inspector reimplements a small deterministic slice of those mechanics. Its workbooks, gold key, and illustrative ballots are newly authored; it does not redistribute the original material or replay original model responses.</p>
        <h3>Measured here, not inherited</h3>
        <p>The unedited margin fixture contains <strong>{session.workbook.cells.length} numeric candidates</strong> and <strong>{result.edges.length} resolved dependency edges</strong>. The balanced rule policy produces <strong>{score.tp} true positives, {score.fp} false positive, {score.fn} false negatives, and {score.tn} true negatives</strong> against its authored key. Final-label precision is <strong>{(100 * score.precision!).toFixed(1)}%</strong>, recall is <strong>{(100 * score.recall!).toFixed(1)}%</strong>, and F1 is <strong>{score.f1!.toFixed(2)}</strong>. These values are computed by the same engine during server rendering and reproduced by the domain tests. They are checks on this fixture, not estimates of performance on unseen workbooks.</p>
        <p>The margin checkpoint <code>Calc!B4</code> has two consumers but remains final under the fixture definition. Its range aggregation, output label, and emphasis outweigh the negative consumed-upstream vote. The unused <code>Report!B4</code> scratch formula is a graph sink and becomes a false positive. Dropping that proposed final removes the false positive without changing any formula. That intervention is an illustrative correction against a known key, not an independently evaluated adjudicator.</p>
        <p>The precision policy requires positive support with no negative rule votes. That reduces willingness to mark cells final, but also pushes the legitimate consumed checkpoint into review. This is a derived consequence of the rules, not a trained precision-recall frontier. Agreement among related heuristics is not calibrated confidence.</p>
      </section>
      <section id="method">
        <h2>Mechanics and implementation</h2>
        <h3>One graph, separate semantics</h3>
        <p>The evaluator parses a bounded arithmetic grammar into an expression tree; it never executes input as JavaScript. Supported expressions include finite decimal literals, A1 references, absolute address markers, simple cross-sheet references, unary signs, arithmetic, parentheses, and <code>SUM</code> with bounded rectangular ranges. A cross-sheet range inherits the sheet on its first endpoint. Repeated references collapse into one graph edge. Each directed edge runs from a precedent into its consumer.</p>
        <p>A depth-first evaluation resolves dependencies and detects cycles using the active recursion path. A cycle blocks its participants and dependent calculations, while unrelated components remain usable. Unknown references, division by zero, unsupported functions, reversed ranges, and non-finite results receive explicit errors. No error is replaced by zero, and invalid calculations cannot be adjudicated into valid finals. Runtime sessions are schema-validated, cell identifiers are unique, and ranges are limited to 64 expanded cells.</p>
        <p>After evaluation, seven labeling functions independently vote final, intermediate, or abstain: dependency sink, range aggregation, output lexicon, numeric input, pass-through formula, consumed-upstream status, and semantically backed emphasis. The balanced policy takes a strict vote majority; a tie remains review. The precision policy adds a no-negative-votes gate. A support-sheet role suppresses final proposals even when local formula signals favor them. These policies are explicit browser rules, not a reproduction of the original structural router&apos;s thresholds.</p>
        <h3>What the larger pipeline did differently</h3>
        <p>The original pipeline extracted features across the full workbook before classifying any sheet. Formula normalization and row grouping compressed repeated period calculations while retaining row labels and section context. Model-assisted variants operated on that context through validated outputs, reusable response caches, and repeated votes. A structural router selected a precision-oriented or recall-oriented constituent per sheet, followed by narrowly scoped deterministic pruning. It routed existing classifier outputs; it was not itself an LLM.</p>
        <p>The weak-supervision branch decomposed heuristic signals into abstaining labeling functions and fit their reliability using a binary latent-label EM model. Such fitting has identifiability and correlated-rule risks; a stable posterior is not automatically calibrated. A class-prior operating point adjusted using labeled examples is a tuning decision even if the inner EM update never directly consumes gold labels. The browser intentionally shows raw vote evidence instead of fitting an underdetermined reliability model to eleven cells. It has no EM, conformal calibration, model call, original prompt cache, or original model prediction.</p>
        <h3>Adjudication is a constrained operation</h3>
        <p>The larger pipeline&apos;s second pass could only keep or drop proposed final rows. That preserves a useful invariant: adjudication cannot introduce an out-of-universe final or rescue an omitted final. A failed or membership-mismatched judge needed an explicit degraded outcome rather than partially trusted verdicts. Here, the visitor supplies keep/drop decisions directly. The same prune-only boundary is enforced in the engine, and workbook or policy edits clear old adjudications before recalculation.</p>
        <p>The separate ballot panel is an <strong>authored illustrative record, not actual model output</strong>. It exists to expose disagreement and the difference between vote majority and deterministic policy. It is bound to the exact baseline workbook. Any workbook change disables both that record and the fixed gold comparison; the demo never invents new model votes for new inputs. A recorded majority does not control the live rule decision.</p>
      </section>
      <section>
        <h2>Failure cases and evaluation boundaries</h2>
        <ul>
          <li><strong>Semantic scope:</strong> a sink can be irrelevant, a pass-through can be a displayed result, and an upstream checkpoint can be final within a section. Graph topology is evidence, not the definition of final.</li>
          <li><strong>Correlated evidence:</strong> total-like labels, emphasis, and aggregation often occur together. Counting them separately can double-count one convention. No vote fraction in this demo is presented as a probability.</li>
          <li><strong>Pruning sacrifices recall:</strong> precision-only review cannot add omitted outputs. A complete evaluation must measure false negatives as well as removed false positives, including by sheet or task rather than only pooled counts.</li>
          <li><strong>Restricted arithmetic:</strong> this is not an Excel-compatible engine. Named ranges, dynamic arrays, external workbooks, quoted sheet names, dates, text, volatile functions, and Excel coercion rules are unsupported. The interpreter returns errors rather than pretending to evaluate them.</li>
          <li><strong>Edited gold is not new ground truth:</strong> changing a label, sheet role, emphasis, or formula may change the intended scope. The authored key applies only to the exact workbook, so edited runs retain computation but lose the comparison.</li>
        </ul>
        <p>In the original evaluation, candidate selection and scoring coverage were separate contracts: scoring only labeled candidates can differ materially from scoring every supplied candidate. Prediction-time access to gold must be blocked, not merely avoided by convention. The public classifier takes no gold argument; the key is used only by the comparison function after predictions exist. Because the key ships in the browser and the fixture is intentionally transparent, this is a correctness exercise, not a blind test.</p>
        <p>Repeated development on a small set of workbooks can tune prompts, priors, and routing thresholds to that set. Leave-one-task-out checks and label-preserving perturbations help find brittleness, but they do not make a repeatedly inspected corpus a pristine holdout. Original local scores are therefore not imported here. A credible generalization claim would require separately governed unseen workbooks, a frozen candidate universe and scoring policy, repeated-run uncertainty, and task- or sheet-clustered reporting. This inspector makes no such claim.</p>
      </section>
      <section id="reproduce">
        <h2>Reproduction and public code</h2>
        <ol>
          <li>Reset the margin workbook with the balanced policy. Inspect <code>Calc!B4</code>: <code>SUM(B2:B3)</code> evaluates to 840 and feeds both a later calculation and a displayed checkpoint.</li>
          <li>Select <code>Inputs!B2</code>, change units from 120 to 200, and recalculate. Revenue becomes 2,400, the expense contribution -1,000, and the margin 1,400. Fixed ballots and gold comparison are unavailable after this edit.</li>
          <li>Reset, select <code>Report!B4</code>, and drop its proposed final. The synthetic comparison becomes TP 2 / FP 0 / FN 0 / TN 9. This is manual review with a visible key, not a model improvement.</li>
          <li>Switch to the failure workbook. Inspect the cycle between <code>Calc!B2</code> and <code>Calc!B3</code>, plus the missing reference on <code>Report!B3</code>. Their errors and dependent failures remain explicit.</li>
          <li>Export a versioned JSON trace, then replay it. The importer validates the session and recomputes results; it does not trust result fields from the uploaded file. There is no random seed because the engine has no random operations.</li>
        </ol>
        <p>The public implementation includes the <a href={`${sourceRoot}/formula.ts`}>bounded formula parser</a>, <a href={`${sourceRoot}/engine.ts`}>dependency and policy engine</a>, <a href={`${sourceRoot}/fixtures.ts`}>new synthetic fixtures</a>, and <a href={`${sourceRoot}/engine.test.ts`}>domain tests</a>. No original workbook or private repository is needed at runtime.</p>
        <pre><code>{'npm run test -- --run --maxWorkers=1 src/lib/projects/spreadsheet-reasoning/engine.test.ts src/components/projects/spreadsheet-reasoning/Inspector.test.tsx src/app/work/projects/spreadsheet-reasoning/page.test.tsx\nnpm run lint -- src/app/work/projects/spreadsheet-reasoning src/components/projects/spreadsheet-reasoning src/lib/projects/spreadsheet-reasoning'}</code></pre>
        <p>Tests cover arithmetic and precedence, absolute and cross-sheet references, range inheritance, dependency errors, cycles, invalid runtime schemas, semantic counterexamples, prune-only membership, stale evidence invalidation, reset, and deterministic replay. Control tests exercise an edit/recalculate/reset sequence, an adjudication, and the failure fixture. This is a reduced, inspectable computation with explicit limits, not a live replacement for the larger model-assisted pipeline.</p>
      </section>
    </article>
  </main>;
}
