import { validateCorpus, type Document } from './engine';

// Fictional engineering documents authored for this demo, not retrieved records.
const drafts: Document[] = [
  { id: 'note-01', title: 'Search latency under load', body: 'Search latency grows when many requests share a cold index. This experiment compares a warm cache with uncached search. A queue records latency before retrieval begins.', tags: ['search', 'latency', 'cache'], year: 2026, kind: 'experiment', topic: 'retrieval', collection: 'lab' },
  { id: 'note-02', title: 'Index partition notebook', body: 'Search across smaller partitions reduces scanned records. Latency depends on partition count and uneven document distribution. Search search search workloads need careful routing.', tags: ['index', 'partition'], year: 2024, kind: 'experiment', topic: 'retrieval', collection: 'lab' },
  { id: 'note-03', title: 'Cache invalidation reference', body: 'Search results in a cache expire when the index revision changes. Keeping old results hides new documents. Cache latency is low but stale search output is incorrect.', tags: ['cache', 'revision'], year: 2023, kind: 'reference', topic: 'storage', collection: 'lab' },
  { id: 'note-04', title: 'Search latency checklist', body: 'Measure the request queue separately from document lookup. Record cold and warm runs. Repeat the same workload with an empty cache.', tags: ['search', 'latency'], year: 2025, kind: 'guide', topic: 'evaluation', collection: 'lab' },
  { id: 'note-05', title: 'RRF rank disagreement', body: 'Search ranks from two channels disagree when one emphasizes titles. Latency measurements are not relevance judgments. Reciprocal rank fusion combines positions rather than raw scores.', tags: ['fusion', 'ranking'], year: 2026, kind: 'experiment', topic: 'retrieval', collection: 'lab' },
  { id: 'note-06', title: 'Storage read path', body: 'Search needs a read path with predictable latency. Storage replication adds durable copies but does not ensure query relevance. A cache changes the read workload.', tags: ['storage', 'replication'], year: 2022, kind: 'guide', topic: 'storage', collection: 'lab' },
  { id: 'note-07', title: 'Search tracing glossary', body: 'Search latency includes queue time and retrieval time. Tracing joins stages with a request token. This glossary distinguishes latency from throughput.', tags: ['tracing', 'latency'], year: 2021, kind: 'reference', topic: 'evaluation', collection: 'lab' },
  { id: 'note-08', title: 'Latency dashboard definitions', body: 'A dashboard groups request duration by route. The slowest percentile is sensitive to sample size. Always publish the observation count.', tags: ['latency', 'dashboard'], year: 2026, kind: 'reference', topic: 'evaluation', collection: 'core' },
  { id: 'note-09', title: 'Search index basics', body: 'A search index maps tokens to document ids. Query tokens select posting lists. Search results contain only documents with exact lexical evidence.', tags: ['search', 'index'], year: 2024, kind: 'guide', topic: 'retrieval', collection: 'core' },
  { id: 'note-10', title: 'Storage checkpoint exercise', body: 'Storage checkpoints preserve the last durable revision. Recovery replays a log after the checkpoint. Replication is independent of checkpoint frequency.', tags: ['storage', 'replay'], year: 2025, kind: 'experiment', topic: 'storage', collection: 'core' },
  { id: 'note-11', title: 'Latency and search archive', body: 'Old notebooks document timeout experiments. They use a small workload and cannot predict current behavior. Historic observations need their configuration.', tags: ['archive'], year: 2020, kind: 'reference', topic: 'evaluation', collection: 'archive' },
  { id: 'note-12', title: 'Exact filter semantics', body: 'Search filters intersect attribute predicates. A strict filter can yield zero results. Dropping a filter changes eligibility, not just latency or performance.', tags: ['filter', 'search'], year: 2026, kind: 'guide', topic: 'retrieval', collection: 'core' },
  { id: 'note-13', title: 'Relevance judgment notebook', body: 'A retrieval evaluation separates tuning queries from held out queries. Independent judgments record relevance. Search latency measures speed, not quality.', tags: ['evaluation', 'relevance'], year: 2025, kind: 'experiment', topic: 'evaluation', collection: 'core' },
  { id: 'note-14', title: 'Deterministic replay format', body: 'Export corpus and query configuration together. Replay recomputes every score. A changed result should fail verification rather than load a forged ranking.', tags: ['replay', 'ranking'], year: 2026, kind: 'reference', topic: 'evaluation', collection: 'core' },
  { id: 'note-15', title: 'Cold search latency notes', body: 'A retired index used compression and asynchronous lookup. The experiment is a fictional example of an archival document.', tags: ['search', 'latency'], year: 2019, kind: 'experiment', topic: 'retrieval', collection: 'archive' },
  { id: 'note-16', title: 'Replication latency budget', body: 'Storage replication waits for acknowledgment. Network delay changes latency. This budget is an illustrative design, not a service level measurement.', tags: ['replication', 'storage'], year: 2023, kind: 'guide', topic: 'storage', collection: 'archive' },
  { id: 'note-17', title: 'Channel depth tradeoff', body: 'Search latency is not computed here. A shallow channel depth removes lower ranked evidence before fusion. Search candidates may disappear even if another channel sees them.', tags: ['ranking', 'depth'], year: 2026, kind: 'experiment', topic: 'retrieval', collection: 'lab' },
  { id: 'note-18', title: 'Token boundary test', body: 'Searcher and latencies are distinct tokens from search and latency. Lexical matching does not infer synonyms. This document exists to expose exact token behavior.', tags: ['tokens', 'test'], year: 2025, kind: 'reference', topic: 'retrieval', collection: 'core' },
];

export function freshCorpus(): Document[] {
  return validateCorpus(drafts);
}
