<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html lang="en">
<head>
  <title>Sitemap — Chimeraforge</title>
  <meta name="robots" content="noindex,nofollow"/>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{
      font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;
      background:#070a10;
      color:#f7f5f2;
      min-height:100vh;
    }
    .wrap{max-width:960px;margin:0 auto;padding:3rem 1.5rem}
    .header{text-align:center;margin-bottom:2.5rem}
    .badge{
      display:inline-block;
      font-size:.75rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase;
      padding:.35rem .9rem;border-radius:999px;
      background:rgba(230,102,55,.15);color:#e66637;
      margin-bottom:1rem;
    }
    h1{font-size:1.75rem;font-weight:700;margin-bottom:.5rem}
    .subtitle{color:#939ba8;font-size:.9rem}
    .count{color:#22b5d3;font-weight:600}
    table{width:100%;border-collapse:collapse;margin-top:1.5rem}
    thead th{
      text-align:left;font-size:.7rem;font-weight:600;letter-spacing:.06em;text-transform:uppercase;
      color:#939ba8;padding:.75rem 1rem;
      border-bottom:1px solid rgba(255,255,255,.08);
    }
    tbody tr{border-bottom:1px solid rgba(255,255,255,.04)}
    tbody tr:hover{background:rgba(230,102,55,.04)}
    td{padding:.65rem 1rem;font-size:.85rem}
    td:first-child{max-width:480px}
    a{color:#22b5d3;text-decoration:none;word-break:break-all}
    a:hover{color:#e66637;text-decoration:underline}
    .pri{
      display:inline-block;padding:.15rem .5rem;border-radius:4px;
      font-size:.75rem;font-weight:600;font-variant-numeric:tabular-nums;
    }
    .pri-high{background:rgba(230,102,55,.15);color:#e66637}
    .pri-med{background:rgba(34,181,211,.12);color:#22b5d3}
    .pri-low{background:rgba(147,155,168,.12);color:#939ba8}
    .date{color:#939ba8;font-variant-numeric:tabular-nums;white-space:nowrap}
    .footer{text-align:center;margin-top:2.5rem;color:#939ba8;font-size:.8rem}
    .footer a{color:#e66637}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="header">
      <span class="badge">XML Sitemap</span>
      <h1>Chimeraforge Sitemap</h1>
      <p class="subtitle">
        <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span> URLs indexed for search engines
      </p>
    </div>
    <table>
      <thead>
        <tr>
          <th>URL</th>
          <th>Priority</th>
          <th>Frequency</th>
          <th>Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemap:urlset/sitemap:url">
          <xsl:sort select="sitemap:priority" order="descending" data-type="number"/>
          <tr>
            <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
            <td>
              <xsl:variable name="p" select="sitemap:priority"/>
              <span>
                <xsl:attribute name="class">
                  pri <xsl:choose>
                    <xsl:when test="$p &gt;= 0.8">pri-high</xsl:when>
                    <xsl:when test="$p &gt;= 0.6">pri-med</xsl:when>
                    <xsl:otherwise>pri-low</xsl:otherwise>
                  </xsl:choose>
                </xsl:attribute>
                <xsl:value-of select="sitemap:priority"/>
              </span>
            </td>
            <td class="date"><xsl:value-of select="sitemap:changefreq"/></td>
            <td class="date"><xsl:value-of select="substring(sitemap:lastmod,1,10)"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
    <p class="footer">
      Generated by <a href="/">Chimeraforge</a>
    </p>
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
