import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { MissionLab } from '@/components/projects/mission-governance/MissionLab';
import cases from '@/lib/projects/mission-governance/reference-cases.json';
import styles from '@/components/projects/mission-governance/mission.module.css';

export const metadata:Metadata={ title:'Mission Governance Lab',description:'Source-derived synthetic mission validation, approval and fault workflows with deterministic mock execution and verifiable replay.',alternates:{ canonical:'/work/projects/mission-governance' } };
const ORIGINAL='https://github.com/Sahil170595/ProjectWyvern';
const ORIGINAL_CODE=`${ORIGINAL}/blob/${cases.referenceCommit}`;
const CODE='https://github.com/Sahil170595/Banterblogs/blob/codex/demo-mission-governance/banterblogs-nextjs/src/lib/projects/mission-governance';

export default function MissionGovernancePage() {
  return <div className={styles.page}>
    <Link href="/work" className={styles.back}><ArrowLeft size={16}/>Work</Link>
    <header className={styles.header}><h1>Mission Governance Lab</h1><p>Validation, operator authority and replay for a mock mission.</p></header>
    <nav className={styles.nav} aria-label="Project sections"><a href="#demo">Lab</a><a href="#findings">Findings</a><a href="#method">Method</a><a href="#reproduce">Reproduce</a><a href={ORIGINAL}>ProjectWyvern</a></nav>
    <section id="demo" aria-label="Mission governance simulation"><p className={styles.scope}>Synthetic simulator / no aircraft control or flight physics. <a href="#limits">Limits</a></p><MissionLab/></section>
    <article className={styles.article} aria-label="Technical write-up">
      <section>
        <h2>The underlying system: ProjectWyvern</h2>
        <p>I implemented <a href={ORIGINAL}>ProjectWyvern</a> as a mission-governance layer between a policy/approval control plane and a vehicle adapter. Its responsibility is not aerodynamic control: it owns mission contracts, validation, allowed lifecycle transitions, operator commands, telemetry normalization, event streaming and replay packaging. Low-level control, estimators and onboard failsafes remain below that boundary.</p>
        <p>The implemented Python service exposes typed mission and command APIs, an in-memory mission/telemetry store, a deterministic mock adapter and a separate MAVSDK adapter. Approval has both a mock client and an HTTP integration client. A telemetry collector and background executor interact through the store; the archive exporter writes mission, validation, timeline, telemetry and optional incident files with SHA-256 content manifests. Those are actual code paths, not evidence of flight-stack qualification.</p>
        <p><strong>Evidence boundary:</strong> this edition is grounded in the public source revision dated March 31, 2026, pinned in the <a href={`${CODE}/reference-cases.json`}>reference artifact</a>. The repository&apos;s mock-based tests exercise validation, execution, operator commands and archive construction. A MAVSDK implementation and an external SITL test script exist, but their presence is not a successful PX4/Gazebo run, hardware qualification, deployment or latency measurement. No operational archives are included here.</p>
        <p>The browser adaptation uses invented local-grid coordinates and synthetic approval/authorization references. Each step performs the mock&apos;s waypoint-poll operation and then the executor&apos;s decision order. The original service uses asynchronous telemetry and executor tasks; this lab serializes them into an explicit deterministic journal. It demonstrates governance boundaries, not flight dynamics or concurrency acceptance.</p>
      </section>
      <section id="findings">
        <h2>Findings: governance is more than a green validator</h2>
        <p>The important question is not whether a route looks plausible. It is whether validation, approval, command receipt, adapter behavior and confirmed mission outcome are kept distinct. Source inspection and fresh synthetic executions reveal several cases where those distinctions matter.</p>
        <h3>Measured fixed cases, not aircraft results</h3>
        <p>The table records new synthetic cases executed against the Python reference and reproduced in the browser port&apos;s focused tests. The patrol has four waypoints, a 30% battery floor, a 0.30 link cutoff and a 1,500 ms freshness limit. Faults change cached health before an executor poll. The completion-first case uses one waypoint to expose the ordering without needing a race.</p>
        <div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Source-derived reference execution results"><table><thead><tr><th>Case</th><th>Mission state</th><th>Progress polls</th><th>Final reason</th></tr></thead><tbody>{cases.execution.map(c=><tr key={c.case}><th scope="row">{c.case}</th><td>{c.state}</td><td>{c.progress} / {c.count}</td><td><code>{c.reason}</code></td></tr>)}</tbody></table></div>
        <p><strong>Warning does not mean blocked.</strong> Missing telemetry gives validation warnings, so an otherwise valid mission reaches awaiting approval. Stale telemetry fails initial validation, but when introduced during execution it returns a <code>blocked.telemetry_stale</code> violation that the current executor logs without stopping. The executor acts only on <code>degraded.</code> and <code>timeout.</code> reason prefixes. The lab records the non-actionable warning as additional browser evidence instead of silently changing that behavior.</p>
        <p><strong>Completion wins the current poll.</strong> The executor checks progress completion before the safety guard. A fault present on the final progress poll therefore does not force RTL. This is a reproducible ordering boundary, not evidence that it is an appropriate policy for aircraft. Reordering the guard would be a source behavior change requiring its own tests and design decision.</p>
        <p><strong>RTL is not confirmed return.</strong> The mock immediately marks itself landed and disarmed when asked to return, while the mission remains <code>rtl</code>. It does not move its stored position to launch, and the executor exits that monitor loop. This lab deliberately stops in RTL rather than animating a fictional return or appending an unearned completion event.</p>
        <h3>Geometry has a less obvious counterexample</h3>
        <p>The validator checks waypoint membership with planar ray casting; it does not validate the segments between waypoints. Load the concave fixture: both endpoints are inside the L-shaped polygon, but their midpoint (50, 50) lies in its notch. Validation passes. That is a derived geometric counterexample to interpreting waypoint containment as complete path containment.</p>
        <p>The same ray-casting rule includes the square&apos;s left edge but excludes its right edge for the tested points. The boundary fixture places one point on the excluded edge and another above the altitude ceiling, producing two concrete failures. A robust operational geometry policy would need an explicit edge convention, segment treatment and coordinate model; this demonstration does not invent those guarantees.</p>
      </section>
      <section id="method">
        <h2>Method and implementation</h2>
        <h3>Typed inputs and a constrained lifecycle</h3>
        <p>The source transition graph has 15 states, including the primary draft-to-completed path and rejection, expiry, pause/resume, RTL, abort, failure and manual-handover branches. The port retains that graph, and its reference test compares every legal and forbidden state pair. The visible controls exercise a subset: validate, approve/reject, start, poll, pause/resume, return and abort. No transition can skip the approval gate.</p>
        <pre><code>{'draft -> validated -> awaiting_approval -> approved\n      -> staging -> executing -> completed\nexecuting -> paused -> resuming -> executing\nexecuting / paused -> rtl or aborted'}</code></pre>
        <p>The browser&apos;s bounded schema rejects non-finite numbers, empty routes, malformed polygons, unknown fields and non-synthetic references. Coordinates use a fictional local metre grid, not WGS84 positions. Mission edits create a new draft and clear previous validation and approval; the running mission is never silently changed under an old approval. These editing and numeric limits are disclosed browser adaptations, not additions to the source&apos;s flight-safety claim.</p>
        <p>Validation collects geofence, altitude, battery, freshness and configured compliance checks. The first failed waypoint per geometry/altitude check is reported. The battery floor and freshness comparisons preserve strict inequalities: equality passes. Missing telemetry is a warning for the two initial health checks; a missing fixture authorization reference is also a warning, while a required but inactive Remote ID fails. These synthetic field checks are not a legal authorization service.</p>
        <h3>Ordering, faults and mock observation</h3>
        <p>Starting enters staging before upload. Upload failure transitions staging to failed; otherwise the executor records executing before arm/start, so a start failure ends executing-to-failed. Pause freezes mock progress; resume passes through the resuming state. Operator return and abort are distinct branches, and duplicate pause/return commands preserve idempotent state behavior.</p>
        <p>Each explicit poll advances one waypoint and 100 ms of a logical clock. Position jumps to the mock&apos;s next waypoint; the connecting lines encode observed checkpoints, not integrated motion. Battery is a supplied health field, not a flight-energy model. The original mock&apos;s battery getter has a configurable drain, but its health getter and normal collector do not invoke that getter; this port does not add a fictional automatic battery drain.</p>
        <p>Runtime safety returns the first violation in this order: unavailable telemetry, battery, link, estimator, freshness, then mission timeout measured from staging. Missing telemetry can therefore mask a later degraded-health condition. The source&apos;s completion-first decision and actionable reason prefixes are preserved. Injecting a fault changes actual cached synthetic state; the next poll computes its consequence rather than playing a scripted incident.</p>
        <h3>Content integrity and replay are separate checks</h3>
        <p>The public system&apos;s <a href={`${ORIGINAL_CODE}/src/wyvern/hashing.py`}>hashing helper</a> sorts JSON keys and computes SHA-256; its <a href={`${ORIGINAL_CODE}/src/wyvern/services/archive_exporter.py`}>archive exporter</a> hashes emitted file bytes. It does not implement a chained event signature. The browser retains the content-manifest idea and adds deterministic command replay.</p>
        <p>An export contains four canonical JSON strings: mission configuration, command journal, event trace and final state. Browser Web Crypto computes a real SHA-256 digest for each string. Verification checks all four digests, parses bounded schemas, reruns the journal from a fresh draft and compares both reconstructed events and final state. The focused tests reject a modified event file and also reject a rehashed event file that disagrees with replay.</p>
        <p>This proves internal byte integrity and reproducibility, not external authenticity. An author can create an entirely different self-consistent bundle and hash it. There is no trusted signature, durable ledger, external approval identity or proof that a vehicle observed any event. Browser number serialization also differs from Python for some floating-point representations, so this versioned bundle is not claimed to be byte-compatible with an original archive.</p>
      </section>
      <section id="limits">
        <h2>What is not demonstrated</h2>
        <p>No aircraft is connected. No flight physics, trajectory tracking, geodesic navigation, onboard failsafe, RC override, estimator, authenticated approval server or PX4/SITL acceptance is implemented in the browser. Manual-handover and expiry graph edges are retained but have no interactive command here. Waypoint hold durations and mission-type-specific behaviors are outside this edition.</p>
        <p>The source separates policy, autonomy and flight-control responsibilities, but architectural intent alone does not prove an enforced end-to-end authority hierarchy. Its stores and event buffers are in memory. A lifecycle command receipt can precede adapter success; mocks and interface tests cannot certify physical execution. The browser also omits concurrent polling, network faults, multi-vehicle arbitration, durable archive storage and API idempotency-key handling.</p>
        <p>The original README lists latency/freshness and safety objectives. They are targets, not measured outcomes here. The current findings are exact fixed-case simulator observations, not statistical reliability estimates or evidence of operational compliance. These limits are why the interface shows both mission state and mock armed/in-air state instead of collapsing them into a single success badge.</p>
      </section>
      <section id="reproduce">
        <h2>Reproduce the decisions</h2>
        <ol>
          <li>Load the patrol. Validate, approve the synthetic mission and start. Step once, pause and resume, then step to completion. Inspect each state transition and checkpoint.</li>
          <li>Reset and repeat the gate sequence. Inject low battery before the first step; the next poll enters RTL after one checkpoint. Reset and try stale or missing telemetry instead: warnings are recorded, but execution can continue.</li>
          <li>Load the boundary fixture and validate to see both geometry and altitude failures. Load the concave fixture and inspect the route crossing its notch despite passing endpoint checks.</li>
          <li>Open Advanced settings, edit a waypoint or limit, then apply. The mission returns to draft and prior approval is cleared. All locations and references must remain synthetic.</li>
          <li>Verify and export the bundle. Paste an export into the bundle verifier; changing event content breaks its digest. Updating that digest alone still fails the deterministic replay comparison.</li>
        </ol>
        <p>The engine, fixtures, reference cases and integrity verifier are available in <a href={CODE.replace('/blob/','/tree/')}>the public demo source</a>. Source evidence for the underlying system includes <a href={`${ORIGINAL_CODE}/src/wyvern/services/validation.py`}>validation</a>, <a href={`${ORIGINAL_CODE}/src/wyvern/services/executor.py`}>the executor</a>, <a href={`${ORIGINAL_CODE}/src/wyvern/vehicle/mock_adapter.py`}>the mock adapter</a> and <a href={`${ORIGINAL_CODE}/tests/test_executor.py`}>executor tests</a>. From the repository&apos;s Next.js app, using installed dependencies:</p>
        <pre><code>{'npm test -- --run src/lib/projects/mission-governance src/components/projects/mission-governance --maxWorkers=1\nnpm run lint -- src/app/work/projects/mission-governance src/lib/projects/mission-governance src/components/projects/mission-governance'}</code></pre>
        <p>Web Crypto requires HTTPS or localhost. No provider calls, model downloads or operational datasets are required. The article is server-rendered; the lab and hash/replay checks run locally in the browser.</p>
      </section>
    </article>
  </div>;
}
