import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import ServiceLab from '@/components/projects/customer-service/ServiceLab';
import styles from '@/components/projects/customer-service/service.module.css';
import { measureControls } from '@/lib/projects/customer-service/measurements';

const source = 'https://github.com/Sahil170595/Banterblogs/tree/codex/demo-customer-service/banterblogs-nextjs/src/lib/projects/customer-service';
export const metadata: Metadata = {
  title: 'Customer Service Environment',
  description: 'A synthetic, human-operated service environment with guarded tools, inspectable state transitions, and branch-coherent reward evaluation.',
  alternates: { canonical: '/work/projects/customer-service' },
};

export default function CustomerServicePage() {
  const measurements = measureControls();
  return <main className={styles.page}>
    <Link href="/work" className={styles.back}><ArrowLeft size={15} aria-hidden />Back to work</Link>
    <header className={styles.header}>
      <span className={styles.eyebrow}>Agents / state-grounded evaluation</span>
      <h1>Customer Service Environment</h1>
      <p>Identity-bound tools, synthetic orders, and rewards grounded in what actually changed. A reduced browser adaptation operated by you, with optional scripted controls. No live LLM, payment processor, or carrier connection.</p>
      <nav className={styles.nav} aria-label="Project sections"><a href="#demo">Environment</a><a href="#underlying-system">Underlying system</a><a href="#findings">Findings</a><a href="#method">Method</a><a href="#reproduce">Reproduce</a><a href={source} target="_blank" rel="noreferrer">Public source <ExternalLink size={12} className="inline" aria-hidden /></a></nav>
    </header>
    <ServiceLab />
    <article className={styles.article}>
      <section aria-labelledby="question">
        <span className={styles.eyebrow}>Engineering question</span>
        <h2 id="question">When is a service task actually resolved?</h2>
        <p>A support agent can say all the right things while changing the wrong record. It can refund the first of two charges instead of the redundant one, promise a replacement with no stock, or describe a carrier request as a completed cancellation. Even a seemingly successful database state is insufficient: an agent might reach it by giving both a refund and a replacement, or by acting before the customer selected a remedy.</p>
        <p>I implemented this browser environment to make those distinctions inspectable. The visitor acts as the agent against a small, deterministic service world. Each tool validates its arguments and ownership, checks policy, and either commits one effect or returns an error without changing the ledger. Evaluation then checks the final world, the order of evidence, the scope of the recorded customer choice, and the supported structured report. A successful sentence is never substituted for a refund row.</p>
        <p>The public cases, order identifiers, products, customer requests, and scripts were authored for this demo. They are synthetic, not customer records. The environment is an adaptation, not a full service backend or a production authentication system. Its useful object is the executable contract between an action, its effect, and the reward it is allowed to earn.</p>
      </section>
      <section id="underlying-system" aria-labelledby="underlying-title">
        <span className={styles.eyebrow}>Underlying system / source-reviewed engineering</span>
        <h2 id="underlying-title">A complete episode pipeline, not just a scoring widget</h2>
        <p>The underlying Python service environment is substantially broader than this browser edition. Its implemented pipeline combines an assistant role, a generated-customer role, a tool-call parser, an episode runner, an episode-local database, policy predicates, a transactional registry, and a trajectory-based evaluator. It also includes a command-line runner and an HTML trace viewer. The source registry declares nine service tools and six evaluation tasks, each with competent, empty, near-miss, and forbidden control trajectories: 24 declared controls. These are source-backed implementation counts, not throughput measurements or evidence of policy training.</p>
        <ol>
          <li><strong>Initialize an isolated world.</strong> Typed records cover users, products, stock, orders, items, payments, shipments, returns, refunds, intercepts, and notifications. Reset deep-copies a fixture. Referential-integrity checks, deterministic state digests, snapshots, and semantic diffs make later mutations inspectable.</li>
          <li><strong>Keep two information views separate.</strong> The customer role receives its own hidden goal and visible dialogue. The assistant sees customer messages, its own raw output, and tool observations. The customer object has no database or registry reference; separation is structural, not merely an instruction in a prompt.</li>
          <li><strong>Run bounded dialogue and action loops.</strong> An outer loop exchanges customer turns; an inner loop permits tool work before a customer-visible response. Malformed output, provider failures, repeated activity without new evidence, and budget exhaustion terminate with named reasons rather than hanging or being misreported as a satisfied customer.</li>
          <li><strong>Validate and dispatch against trusted identity.</strong> The registry checks a strict argument model, derives an episode-scoped idempotency identity, executes on a working copy, and commits only successful state changes. Ownership failures and missing records share a public observation; private audit reasons remain in the evaluator trace.</li>
          <li><strong>Score and preserve the receipt.</strong> Initial/final database snapshots and the ordered trajectory feed outcome predicates, process checks, communication checks, efficiency accounting, deductions, and ceilings. Recorded episodes can be re-scored without another model call.</li>
        </ol>
        <h3>Protocol control brings a larger correctness surface</h3>
        <p>The underlying assistant uses JSON calls embedded in ordinary text rather than native structured tool blocks. The parser must therefore distinguish executable calls from quoted examples, preserve only safe visible prose, scrub residual call markup, and return recoverable parse errors. Fenced examples are not executed. A closing-tag stop sequence limits generation to one call, but the provider omits that matched sequence from returned text; the adapter restores it only when the stop reason establishes that it really occurred. That is a concrete latency-versus-protocol-complexity tradeoff, not an assumption that custom parsing is generally preferable.</p>
        <p>Acting-turn prose is kept privileged by the runner. Tool observations are encoded through an explicit public-field whitelist, excluding private audit metadata. The source isolation tests contain both negative checks for leaked calls, database fields, goals, and verifier content, and positive checks that the privileged histories really retain the evidence they should. A source test is evidence of an encoded contract; I have not rerun that original suite or its provider-backed execution during this browser build.</p>
        <h3>State predicates are necessary, but not sufficient</h3>
        <p>The original evaluator does not equate the generated customer completion flag with success. That flag is persuadable; it is not proof that money or stock moved correctly. The outcome layer selects the best individually consistent branch, not a union of fragments from conflicting alternatives. Ordered event coverage is tied to attributable terminal effects, and consent is scoped to the selected writes. Communication facts, contradictions, unsupported claims, foreign-data disclosure, and relevant verification before mutation are evaluated separately from the achievement itself.</p>
        <p>Damage also has its own semantics. A refused forbidden attempt is different from a committed effect. Impact is derived from action and current lifecycle state, so an authorized irreversible refund is not automatically a failure. Committed unjustified effects, concealment, and compensation affect deductions and ceilings. An apology is not an inverse transaction. The optional communication judge has a bounded adjustment role; deterministic evidence and safety ceilings remain authoritative. The browser deliberately replaces that richer communication layer with explicit typed reports, rather than presenting menu selections as language understanding.</p>
        <h3>Findings from the underlying implementation review</h3>
        <p><strong>Preserved state cannot certify achievement.</strong> The original documentation records an absence-only reward flaw caught by the null control; the evaluator now explicitly limits branches made only of preserved-state predicates. The lesson is to require positive evidence or achievement, not award outcome credit simply because ownership or stock remained unchanged. The split-tender branch below applies that lesson to newly authored data.</p>
        <p><strong>Replaying a guarded tool can erase the failure you meant to evaluate.</strong> The original reward-gate tests preserve terminal worlds from intentionally forced invalid effects. Re-dispatching those actions through a registry that correctly refuses them would change the experiment from committed harm into a denied attempt. The source therefore distinguishes grading a saved compromised-world control from executing a normal guarded script. This browser never bypasses its tools; its negative committed-effect example instead uses individually permitted but jointly incompatible remedies.</p>
        <p><strong>A repeated call is not always a stalled round.</strong> The underlying runner evaluates progress over a whole tool round. A duplicate observation followed by a new read or a successful write must not terminate productive work. The source resilience tests encode those counterexamples and single-owner retry behavior to avoid multiplying provider retry budgets. This browser accepts one command per step and uses a simpler repeated-observation guard; it does not reproduce the full multi-call round semantics.</p>
        <p>These are design findings supported by the inspected implementation and its tests, not fresh benchmark results. No original task-specific rewards, live-model scores, or training improvements are carried into the public table. The browser exposes the core state/permission/reward contract on replacement fixtures. It omits the generated dialogue, text protocol, provider adapter and retries, private audit channel, richer entity graph, natural-language communication evaluator, full efficiency model, and original control corpus. Its local rubric has its own version and cannot be numerically compared with the reward scale of the underlying evaluator.</p>
      </section>
      <section id="findings" aria-labelledby="findings-title">
        <span className={styles.eyebrow}>Computed controls / synthetic fixtures</span>
        <h2 id="findings-title">Correct money is not necessarily the correct refund</h2>
        <p>The table below is computed by the current engine during server rendering. Every row starts from a fresh synthetic fixture with a 4,800-cent order total. Stock is two units unless the row specifies no preferred stock. The action count includes evidence reads, scripted customer choices, writes, and structured reports. Effects count only actions that changed world state. These are deterministic control results, not model performance, training gains, or a held-out benchmark.</p>
        <div className={styles.tableWrap}><table>
          <thead><tr><th scope="col">Control</th><th scope="col">Actions</th><th scope="col">Effects</th><th scope="col">Reward</th></tr></thead>
          <tbody>{measurements.map(m => <tr key={m.label}><td>{m.label}</td><td>{m.actions}</td><td>{m.effects}</td><td>{m.score.toFixed(2)}</td></tr>)}</tbody>
          <caption>Recomputed from <a href={`${source}/measurements.ts`}>measureControls</a> and <a href={`${source}/scripts.ts`}>scriptedActions</a>, using service-reward.v1. An empty episode scores 0.00. Fixture-specific numbers do not describe an LLM.</caption>
        </table></div>
        <h3>1. Identity and money belong to different checks</h3>
        <p>Refunding either full capture is mechanically possible after the exact payment and amount have been authorized in this sandbox. Both payments belong to the authenticated synthetic account and both have captured funds. But only refunding <code>PAY-B</code> fulfills the duplicate-charge goal. The reward branch therefore requires the specific payment record, not merely 4,800 cents leaving the account. Refunding <code>PAY-A</code> is a permitted tool effect but an incorrect task outcome, and receives the off-goal-effect ceiling.</p>
        <h3>2. Two plausible remedies can form one bad trajectory</h3>
        <p>For the damaged lamp, return-plus-refund and return-plus-replacement are alternatives. Each can succeed alone. A trajectory that completes both consumes stock and money, even if each individual operation was valid and a later structured report describes one of them truthfully. No candidate branch accepts that combined world. The evaluator does not add partial credit across alternatives; committed writes must fit a single branch.</p>
        <h3>3. Useful partial outcomes must remain partial</h3>
        <p>A carrier intercept request leaves the order shipped. Its branch credit and total ceiling are 0.70. A preferred-finish stock alert records a notification but does not deliver a lamp or return funds, so its ceiling is 0.60. These values are local design choices, not empirical estimates of customer satisfaction. The visualization keeps the unresolved physical state visible instead of silently marking delivery complete.</p>
        <h3>4. Restraint needs positive evidence</h3>
        <p>The split-tender fixture contains two distinct half-captures that sum to the order total. Leaving the database untouched is necessary, but not sufficient. The successful branch also needs the order read, payment read, and a subsequent supported split-tender report. An empty trajectory earns no credit. That prevents an absence-shaped invariant from becoming a free reward for doing nothing.</p>
      </section>
      <section id="method" aria-labelledby="method-title">
        <span className={styles.eyebrow}>Mechanics / implementation</span>
        <h2 id="method-title">Validate, bind identity, then publish state</h2>
        <p>The engine lives outside React. <a href={`${source}/model.ts`}>Typed schemas</a> validate configuration, static fixtures, action envelopes, and strict tool arguments. Money is integer cents; the order total must be even because the split-tender case constructs two equal payments. Stock is an integer from zero through six. Invalid configurations fail explicitly. Tool errors are values with stable codes, not an invitation to invent a fallback result.</p>
        <p>The trusted session identity is fixed when the episode starts. A tool cannot supply a different owner or an idempotency key: extra fields are rejected by the tool schema. Every order-bound tool resolves ownership before exposing related payments or effects. A missing order and a foreign order return the same public result, preventing the observation channel from becoming an existence oracle. The foreign sentinel contains no real personal data.</p>
        <p>Each step works on a deep copy of the session. The event records the state immediately before and after dispatch, the validated action, result, and impact class. A denial publishes the unchanged world. Cancellation changes only the order status; a separate refund is still necessary to fulfill the warehouse goal. Returns apply only to delivered items. Replacement requires an authorized return and available stock, consumes one unit, and persists one replacement per original item.</p>
        <p>Refunds are bounded by captured funds minus all refunds already committed to that payment. The environment derives the refund-effect identity from the order, payment, and amount; it is not caller-controlled. Exact retries find the existing effect and do not move more money. Changing the amount creates a new request, which must still pass the remaining-balance check. Replacement retries use the persisted original-item association, so changing the finish cannot allocate a second unit.</p>
        <h3>Authorization is explicit and narrow</h3>
        <p>The customer-choice control is a scripted input to the environment, not a simulated conversation or a live customer. It binds a remedy to the order; refunds also bind payment and exact cents, while replacement and notification bind the finish. A write without the matching choice returns <code>consent_required</code>. Changing that choice can authorize a second, individually valid effect, but does not rewrite the original goal or erase earlier actions. This is how the conflicting-remedy control exposes the difference between per-call permission and trajectory correctness.</p>
        <h3>One coherent branch, with ordered evidence</h3>
        <p><a href={`${source}/reward.ts`}>The evaluator</a> tests each outcome branch separately. Required world predicates establish the achievement and preserve the incompatible alternatives. Ordered successful events establish the evidence and actions leading to it. A write counts toward event coverage only when it actually changed the world; an idempotent replay cannot manufacture another achievement. Finally, a structured report must occur after the necessary evidence and effects, and be supported by the world at the moment it was emitted.</p>
        <p>The local rubric combines outcome credit (weight 0.70), relevant evidence before writes (0.20), and a supported report (0.10). Refused attempts, invalid calls, redundant write retries, and state-divergent reports add deductions. Then ceilings apply: incomplete resolution is capped, unverified mutations cannot certify full success, and effects outside every coherent branch force a negative score. The total is bounded from -1 to 1 and stamped <code>service-reward.v1</code>. A component vector without its deductions and ceilings is not the authoritative score.</p>
        <p>Impact is attached using the pre-action state. A warehouse cancellation is reversible within this model; refunds, replacement allocation, and carrier requests represent external commitments. That label describes consequence, not correctness. A justified refund is allowed and valuable. A denied request is recorded and penalized as an attempt, but is not confused with committed financial damage.</p>
        <h3>Finite activity and reproducible receipts</h3>
        <p>Three identical tool observations without a state change close the episode as <code>no_progress</code>; the episode is capped at 48 actions. Customer-choice events reset the repeated-observation counter but do not bypass the total budget. Export includes version, configuration, synthetic initial/final worlds, actions, event snapshots, termination, and reward. No random generator is used, so the exported seed is explicitly null. Import validates version and identity, replays actions from a fresh fixture, and rejects initial-state, final-state, or termination receipts that disagree with the recomputed episode. Imported event observations and rewards are recomputed, never trusted as proof.</p>
      </section>
      <section aria-labelledby="limits-title">
        <span className={styles.eyebrow}>Failure cases / fidelity boundary</span>
        <h2 id="limits-title">What this environment does not prove</h2>
        <p>A browser ledger is not a secure backend. Anyone with developer tools can edit their local JavaScript state; the identity boundary demonstrates dispatch semantics, not resistance to a hostile browser. Production ownership checks, transactions, and idempotency must execute on a trusted service. Exported traces are replay receipts, not signed attestations. The replay check validates final-state agreement, not the authenticity of an external run.</p>
        <p>This adaptation uses one item per order, immediate committed refunds, one coarse shipped state, and two catalog finishes. It does not model multi-line returns, split shipments, authorization holds, partial capture settlement, payment-provider failures, carrier acceptance, asynchronous fulfillment, time windows, or compensating transactions. A replacement effect means stock was allocated in the synthetic ledger; it does not mean a parcel was shipped.</p>
        <p>Reports are typed assertions from a fixed menu. There is no natural-language parser, conversational judge, assistant model, generated customer, hidden model state, or adversarial prompt-injection evaluation. The scripts are explicit control trajectories, not a policy learned from experience. They do not adapt to arbitrary goals, and a script intended for one case can fail when paired with another. Those failures are real tool results, not a hidden rewrite to a successful path.</p>
        <p>The rubric is also intentionally inspectable and limited. It checks branch-specific facts rather than every possible real-world grievance; <code>refunded</code> means some refund exists, while the branch separately verifies the exact payment and amount. A correct disclosure of a mistake does not undo its effect. Repeating reads may be appropriate after fresh external evidence in a deployed system, whereas this frozen world has no external updates. Local control scores should never be pooled with scores from a different reward version or represented as a general safety guarantee.</p>
      </section>
      <section id="reproduce" aria-labelledby="reproduce-title">
        <span className={styles.eyebrow}>Reproduction / public code</span>
        <h2 id="reproduce-title">Reproduce effects, not just the final number</h2>
        <ol>
          <li>Start a fresh damaged-lamp case with stock 2 and total 4,800 cents. The verified script reads the order and inventory, records the selected finish, authorizes a return, creates one replacement, then reports it. Stock falls from two to one and the full-resolution branch completes.</li>
          <li>Start the same case with the refund-plus-replacement conflict script. Both effects persist, but every outcome branch fails coherence. Compare its trace with the verified remedy; do not infer success from the presence of one valid refund row.</li>
          <li>Compare two full captures with two legitimate payments. The verified duplicate path refunds only the second full capture. The split-tender path changes no financial state, but must verify and report the evidence.</li>
          <li>Run the claim-only, oversized-refund, cross-account, and repeated-read controls. Inspect the observation and before/after snapshots. Reset, export JSON, and import it to recompute the recorded actions from the same initial fixture.</li>
        </ol>
        <p>In a checkout of the public branch, use the existing project dependencies and run the focused, single-worker domain suite and scoped lint:</p>
        <pre><code>{`cd banterblogs-nextjs\nnpm run test -- --run src/lib/projects/customer-service --maxWorkers=1\nnpm run lint -- src/lib/projects/customer-service src/components/projects/customer-service src/app/work/projects/customer-service`}</code></pre>
        <p>The <a href={`${source}/engine.test.ts`}>engine tests</a> exercise atomic denial, ownership indistinguishability, caller-identity rejection, refund bounds and retries, stock preservation, mutually exclusive branches, state-divergent reports, episode termination, and replay. <a href={`${source}/controls.test.ts`}>Control sweeps</a> reproduce the table and sweep stock and order totals. These checks validate the local adaptation; they do not substitute for integrated route, build, accessibility, or browser QA.</p>
        <p>Public implementation: <a href={source}>engine, schemas, reward, fixtures, scripts, and tests</a>. The source is self-contained within this project directory and makes no provider calls or cross-repository runtime imports.</p>
      </section>
    </article>
  </main>;
}
